### ISSUE TITLE
上传代码

### ISSUE THREAD

**Issue by freya-7** [double125/MADTP#2]
您好，我觉得这是一篇很好的工作，想多学习一下。请问您可以分享一下代码吗

**Comment by double125** [comment]
I have released the official code of our MADTP methods. If you have any other issues, please let me known.

**Comment by double125** [comment]
I have released the official code of our MADTP methods. If you have any other issues, please let me known.

**Comment by freya-7** [comment]
Thank you, this helps me a lot.
