### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by Researcher-Feng** [double125/MADTP#3]
![Snipaste_2024-09-05_21-46-35](https://github.com/user-attachments/assets/5776dabc-4863-4004-824c-f3d185b34b08)
Hey, where is the code? Are you kidding everyone here??????

**Comment by double125** [comment]
Dear Feng,
       I have released the official code of our MADTP methods. If you have any other issues, please let me known.
     
 Jianjian, Cao

**Comment by double125** [comment]
code has been released !!!
